# Generated by Django 5.2.5 on 2025-08-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_email_alter_user_full_name_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='core.service', verbose_name='الخدمة'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['title'], name='core_servic_title_06a5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['description'], name='core_servic_descrip_397600_idx'),
        ),
    ]
