# Generated by Django 5.2.5 on 2025-08-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_consultationrequest_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='service',
        ),
    ]
